services:
  - type: web
    name: climate-analysis-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd webapp && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 